---
AWSTemplateFormatVersion: '2010-09-09'
Transform: CfnGitSync
Parameters:
  RepositoryOwner:
    Type: String
    Default: ''
  RepositoryName:
    Type: String
    Default: ''
Resources:
  InitialPlaceholder:
    Type: AWS::CloudFormation::WaitConditionHandle
