name: validate-cloudformation

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'stacks/templates/**'
  pull_request:
    paths:
      - 'stacks/templates/**'

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          find stacks/templates -name '*.yaml' -exec cfn-lint -t {} \;
