name: setup-deployments

on:
  pull_request:
    paths:
      - 'stacks/environments.yaml'

jobs:
  add-new-deployments:
    runs-on: ubuntu-latest
    container: 
      image: theonestack/cfhighlander:latest
      options: --user 1001 # this user is required as this is the uid used by the checkout step
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: create deployment files
      env:
        GITHUB_ORG_NAME: ${{ github.repository_owner }}
        GITHUB_REPO_NAME: ${{ github.repository }}
      run: make setup-deployments
    - uses: EndBug/add-and-commit@v9
      with:
        message: adds deployment stacks templates and deployment config files
        default_author: github_actions
        add: stacks/